/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bz.metric.visual;

import bz.metric.control.MetricControl;
import bz.metric.dao.GrupotagDAO;
import bz.metric.nac.MetricNac;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author bzsantos
 */
public class JMetric extends javax.swing.JFrame {

    /**
     * Creates new form JMetric
     */
    public JMetric() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtClassificar = new javax.swing.JTextField();
        btnClassificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaNac = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        btnCSV = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        txtContador = new javax.swing.JSpinner();
        btnMetricaskm = new javax.swing.JButton();
        btnFiltrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setText("Beta");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Metacognitive");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(522, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        txtClassificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtClassificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 240, 40));

        btnClassificar.setBackground(new java.awt.Color(204, 204, 204));
        btnClassificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClassificar.setText("Classificar");
        btnClassificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnClassificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Inserir metadado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        listaNac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(listaNac);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 300, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Resultado: Métricas Cognitivos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        btnCSV.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCSV.setText("CSV");
        getContentPane().add(btnCSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 80, 60));

        btnImprimir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnImprimir.setText("Imprimir");
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, 40));

        txtContador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 50, 40));

        btnMetricaskm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMetricaskm.setText("Métricas KM");
        btnMetricaskm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetricaskmActionPerformed(evt);
            }
        });
        getContentPane().add(btnMetricaskm, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 120, 70));

        btnFiltrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 80, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bz/metric/visual/fnd.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 750, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClassificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassificarActionPerformed
        // TODO add your handling code here:
        
        MetricNac mnac = new MetricNac();
        MetricControl mc = new MetricControl();
        
        
        
        DefaultListModel model = new DefaultListModel();
        
       
        try {
            
            
          //  mc.cadmetric(txtClassificar.getText());
            mnac.mets(txtClassificar.getText());
        
        double x = (mnac.nc()/2);
//        String nc = Double.toString(x);
        
//        int cont = (int) txtContador.getValue();
//        
//        
//        int[] vetor = new int[cont];     

       String[] n = new String[3];
       n[0] = Double.toString(mnac.ka());
       n[1] = Double.toString(mnac.kb());
       n[2] = Double.toString(x);
      
               
      
      // String teste = n[0];
        
        
     
        
        model.addElement("KMCA: " + n[0]); 
        model.addElement("KMCB: " + n[1]);        
        model.addElement("NAC: " + n[2]);
       
        
//         model.addElement(mnac.getEFMO()); 
//         model.addElement(mnac.getEFGO()); 
//         model.addElement(mnac.getEFGP()); 
//         model.addElement(mnac.getEFMP()); 
        
         
        
        
        
//            JOptionPane.showMessageDialog(null, "Valor atribuido para EMO: " + mnac.getEFMO()
//                    + "\n Valor atribuido para EGO: " + mnac.getEFGO()
//                    + "\n Valor atribuido para EGP: " + mnac.getEFGP()
//                    + "\n Valor atribuido para EMP: " + mnac.getEFMP()
//                    + "\n Valor atribuido para NAC: " + (mnac.nc()/2));
            
            
            
            listaNac.setModel(model);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(JMetric.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
      
        
      
        
    }//GEN-LAST:event_btnClassificarActionPerformed

    private void btnMetricaskmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetricaskmActionPerformed
        // TODO add your handling code here:
        
        MetricNac mnac = new MetricNac();
        MetricControl mc = new MetricControl(); 
         
        try {
        
        mnac.mets(txtClassificar.getText());
        
        
       
            JOptionPane.showMessageDialog(null, "Valor atribuido para EMO: " + mnac.getEFMO()
                    + "\n Valor atribuido para EGO: " + mnac.getEFGO()
                    + "\n Valor atribuido para EGP: " + mnac.getEFGP()
                    + "\n Valor atribuido para EMP: " + mnac.getEFMP()
                    + "\n Valor atribuido para NAC: " + (mnac.nc()/2));
        } catch (SQLException ex) {
            Logger.getLogger(JMetric.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_btnMetricaskmActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        
        
        GrupotagDAO gt =  new GrupotagDAO();
        gt.insereproceduremeta();
        
    }//GEN-LAST:event_btnFiltrarActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMetric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMetric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMetric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMetric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMetric().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCSV;
    private javax.swing.JButton btnClassificar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnMetricaskm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaNac;
    private javax.swing.JTextField txtClassificar;
    private javax.swing.JSpinner txtContador;
    // End of variables declaration//GEN-END:variables
}
